### ISSUE TITLE
Avaliar a Documentação e fazer uma estimativa do que precisará ser desenvolvido

### ISSUE THREAD

**Issue by roywaked** [roywaked/nfce#1]

**Comment by roywaked** [comment]
@fcrozetta , 
gostaria que avaliasse o que precisa ser desenvolvido. e o tempo estimado para cada item.

- Comunicação WerbService
- XML
- QrdCode
- Cobol
- Outros

**Comment by fcrozetta** [comment]
Aparentemente usaremos apenas um novo webservice para nfe, então não precisaremos modificar muita coisa nos fontes. 
Pelo que vimos, podemos manter a mesma chamada de nfe (nfe-envio.php,nfe-status.php,etc...) passando como autorizadora NFCE-ESTADO.

Testamos o qrcode versão 2.0 (usado no novo NFCe), e estamos conseguindo gerar corretamente. 
O xml está sendo enviado e parece estar OK (a consulta ainda não está retornando dados para termos 100% de certeza)

O cobol talvez precise alterar algumas chamadas, mas o txt segue o mesmo padrão do que era enviado antes.
